name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: GitHub Actions
          GIT_CONFIG_EMAIL: gh-actions@example.com
      - name: Deploy to nightly branch 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: nightly
          FOLDER: dist
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: GitHub Actions
          GIT_CONFIG_EMAIL: gh-actions@example.com
